### PR TITLE
General fixes

### PR DESCRIPTION
**Pull request by keslerm**
* Tweak regex to not be greedy since we're looking for a single boundry
* Fix unclosed client error in example
* Remove the `.do` part from the API url since it looks like FPL changed that at some point.

### CODE REVIEW

**Comment by keslerm** [comment]
Hi I was going to try to port this into home-assistant but needed to fix a couple of minor things to make it work.

**Comment by Klathmon** [comment]
Oh hell yeah!

I attempted to use this in home assistant back when I made it, but between life getting in the way and some issues I ran into on home assistant I never finished it.


I'm happy to merge this, and I'd be fine with migrating this over to you as the owner if you want. I'm going to add you as a maintainer here on github, and if you can let me know your pypi username I can give you "maintainer" permissions over there as well so you can cut new releases.

If you want to take a glance over it, [here](https://github.com/home-assistant/home-assistant/compare/dev...Klathmon:new-fpl-component) is what I had going on the home-assistant python side, but I didn't get too far. At the time home assistant was going through a transition on how these kind of components were created, and I'm already not too hot with python since I haven't used it heavily for almost 10 years now, so it was a bit of a mess! But it might at least help out a bit!

**Comment by keslerm** [comment]
Cool, yeah i'm going to try to knock this out tomorrow after I update my hass install tonight.

My pypi username is the same as my github one.

**Comment by Klathmon** [comment]
Cool! You're added as a maintainer on PyPi. Let me know if you want me to test anything as an FPL customer. I am on a pretty old version of Home assistant (version 0.86.4 right now), mostly out of sheer laziness and because it's been running rock solid for months now and I haven't had to touch anything, but I'm willing to do the upgrade and test this out if you need me to!

**Pull request merged**
